applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/QueryEditor.xaml
applications/lokqlDx/QueryEditor.xaml.cs

Adds a very basic busy indicator and interlock to prevent parallel queries

LokqlDX busy indicator

---

libraries/FileFormats/CsvSerializer.cs
libraries/FileFormats/JsonObjectArraySerializer.cs
libraries/KustoLoco.Core/BabyKustoEngine.cs
libraries/KustoLoco.Core/Diagnostics/IrNodeVisualizer.cs
libraries/KustoLoco.Core/KustoQueryContext.cs
libraries/lokql-engine/InteractiveTableExplorer.cs
test/BasicTests/ChunkTests.cs
test/BasicTests/CsvLoadTester.cs
test/BasicTests/OperatorTests.cs
test/BasicTests/TestMethods.cs
test/CoreTests/DynamicTests.cs
test/CoreTests/EndToEndTests.cs
test/CoreTests/KustoDocsTests.cs
test/CoreTests/NegativeTests.cs
test/CoreTests/ScalarFunctionsTests.cs

Add two new settings core.dumpir and core.dumpkl to control display of internal diagnostics

Support dynamic enable of core debug

---

Directory.Packages.Props
KustoLoco.sln
build.ps1
libraries/AppInsightsSupport/AppInsightsSupport.csproj
libraries/AppInsightsSupport/ApplicationInsightsLogLoader.cs
libraries/KustoLoco.Core/KustoQueryResult.cs
libraries/KustoLoco.Core/Settings/KustoSettingsProvider.cs
libraries/KustoLoco.Core/Util/TypeMapping.cs
libraries/lokql-engine/InteractiveTableExplorer.cs

Add basic support for remote Application Insight queries in lokql
Add linux builds to build.ps1

Appinsights

---

applications/lokqlDx/App.xaml
applications/lokqlDx/App.xaml.cs
applications/lokqlDx/MainWindow.xaml
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/RegistryOperations.cs
applications/lokqlDx/register-application.ps1

Lokqldx now supports jumplists for recent/frequent workspaces

Add support for jumplists

---

Directory.Packages.Props
applications/lokqlDx/MainWindow.xaml.cs
libraries/KustoLoco.Core/Settings/KustoSettingsProvider.cs
libraries/Rendering/KustoResultRenderer.cs
libraries/lokql-engine/InteractiveTableExplorer.cs
samples/Blazor-Static/Pages/Home.razor

Update to latest Kusto language package
Allow settings to control charting

Update to latest VegaGenerator

---

libraries/lokql-engine/BlockBreaker.cs
libraries/lokql-engine/BlockInterpolator.cs
libraries/lokql-engine/BlockSequence.cs
libraries/lokql-engine/Commands/AppInsightsCommand.cs
libraries/lokql-engine/Commands/CommandProcessor.cs
libraries/lokql-engine/Commands/DefineMacroCommand.cs
libraries/lokql-engine/Commands/MacroDefinition.cs
libraries/lokql-engine/Commands/MacroRegistry.cs
libraries/lokql-engine/Commands/RunMacroCommand.cs
libraries/lokql-engine/InteractiveTableExplorer.cs

Macros can now be defined in lokqldx scripts

Add support for macros

---

libraries/FileFormats/CsvSerializer.cs

CsvSerializer now supports  a csv.SkipHeaderOnSave setting to allow for "bare" output

Support skipheaderonsave

---

libraries/KustoLoco.Core/Settings/KustoSettingsProvider.cs
libraries/lokql-engine/BlockInterpolator.cs
test/BasicTests/SimpleFunctionTests.cs
test/LokqlEngineTests/BlockBreakerTests.cs
test/LokqlEngineTests/BlockInterpolationTests.cs

Lokqldx interpolation has been improved to allow use of $left and $right in join expressions

Improve interpolation

---

Directory.Packages.Props

Updated to Kusto Language package 5.6.0

Update to latest Kusto Language version

---

libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInScalarFunctions.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/DatetimeDiffFunction.cs

Provide an initial implementation of datetime_diff

Implement datetime_diff

---

applications/lokqlDx/Copilot.cs
applications/lokqlDx/MainWindow.xaml
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/Preferences.cs
applications/lokqlDx/WorkspaceManager.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInScalarFunctions.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/DatetimePartFunction.cs
libraries/lokql-engine/InteractiveTableExplorer.cs

Implements datetime_part
Provides experimental chatgpt copilot support

Provide experimental copilot support

---

libraries/FileFormats/CsvSerializer.cs
libraries/FileFormats/JsonObjectArraySerializer.cs
libraries/FileFormats/ParquetSerializer.cs
libraries/lokql-engine/BlockInterpolator.cs
libraries/lokql-engine/Commands/MacroRegistry.cs
libraries/lokql-engine/IFileBasedTableAccess.cs
libraries/lokql-engine/NullFileLoader.cs
libraries/lokql-engine/StandardFormatAdaptor.cs
libraries/lokql-engine/TableAdaptorBase.cs
libraries/lokql-engine/TextTableAdaptor.cs
test/LokqlEngineTests/BlockInterpolationTests.cs

Ensure that files are correctly truncated on saving
Provide better warnings of load errors

Serialization improvements

---

Directory.Packages.Props

upgrade nuget packages

---

libraries/KustoLoco.Core/Evaluation/SummaryKey.cs
libraries/KustoLoco.Core/Evaluation/TreeEvaluator.NpmSummarySet.cs

Allow summarize by to list up to 10 properties

Allow summarize by to list up to 10 properties

---

applications/pskql/Properties/PublishProfiles/linux.pubxml
applications/pskql/Properties/PublishProfiles/win64.pubxml
applications/pskql/PsKqlCmdlet.cs

Improve edit-kql by supporting more property types

Improve edit-kql by supporting more property types

---

Directory.Packages.Props
libraries/KustoLoco.Core/Evaluation/BuiltIns/CustomFunctions.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/PadLeftFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/PadRightFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/SubstringFunction.cs
test/BasicTests/SimpleFunctionTests.cs

- introduce sustring overload
- introduce padleft and padright functions

- Update nuget dependencies

---

Directory.Packages.Props
libraries/KustoLoco.Core/ColumnTypeInferrer.cs
test/ExtendedCoreTests/ColumnInferenceTests.cs

Improve TypeInferrer so that long floatingpoint numbers are inferred

Update nuget dependencies and improve type-inference

---

Directory.Packages.Props
applications/lokqlDx/MainWindow.xaml.cs
libraries/Rendering/KustoResultRenderer.cs

Improve UI behaviour when no query results

---

applications/lokqlDx/QueryEditor.xaml
applications/lokqlDx/QueryEditor.xaml.cs

Lokqldx now supports drag-and-drop.
Dragging a data or csl file into the editor causes a ".load/.run" statement to be inserted at the cursor position

Provide drag and drop support for lokqldx

---

applications/lokqlDx/App.xaml.cs
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/WorkspaceManager.cs

Ensure that title and text-window are correctly updated when using "save as"

Improve save-as behaviour for lokqldx

---

Directory.Packages.Props
sourceGeneration/SourceGeneration/KustoFunctionSourceGenerator.cs

Update source generation to  incrememental

Update source generation

---

libraries/lokql-engine/Commands/CommandProcessor.cs
libraries/lokql-engine/Commands/QuickCsvCommand.cs

Adds a .csvdata command for quick import of inline data

Provide a simple way of importing inline data

---

Directory.Packages.Props
applications/lokqlDx/MainWindow.xaml
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/Preferences.cs
applications/lokqlDx/QueryEditor.xaml
applications/lokqlDx/QueryEditor.xaml.cs
applications/lokqlDx/SyntaxHighlighting.xml
applications/lokqlDx/lokqlDx.csproj

mplement simple syntax highlighting

Use AvalonEdit

---

applications/lokqlDx/MainWindow.xaml
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/Preferences.cs
applications/lokqlDx/WebViewExtensions.cs
applications/lokqlDx/WebviewRenderer.cs
libraries/KustoLoco.Core/Settings/KustoSettingsProvider.cs
libraries/Rendering/KustoResultRenderer.cs
libraries/lokql-engine/Commands/IResultRenderingSurface.cs
libraries/lokql-engine/Commands/NullResultRenderingSurface.cs

Use tab control for data/chart view.  
Add buttons to open chart in browser/copy as image
Move datagrid row max to a setting

Improve UI

---

applications/lokqlDx/MainWindow.xaml
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/WebviewRenderer.cs
libraries/lokql-engine/Commands/AddToReportCommand.cs
libraries/lokql-engine/Commands/PptReportTarget.cs
libraries/lokql-engine/ResultHistory.cs

Misc changes

---

applications/lokqlDx/App.xaml.cs
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/MissingWebviewWindow.xaml
applications/lokqlDx/MissingWebviewWindow.xaml.cs

Add code to warn user if webview is not installed

Add code to warn user if webview is not installed

---

applications/lokqlDx/QueryEditor.xaml.cs
global.json

Ensure manifest resources can be loaded for published exe

Safer loading of manifest resources

---

applications/lokqlDx/ApplicationPreferences.cs
applications/lokqlDx/ApplicationPreferencesWindow.xaml
applications/lokqlDx/ApplicationPreferencesWindow.xaml.cs
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/Preferences.cs
applications/lokqlDx/PreferencesManager.cs
applications/lokqlDx/WorkspaceManager.cs

Improve close behaviour,

---

libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInScalarFunctions.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/Operators/DivideFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/IsAsciiFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/IsEmptyFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/IsFiniteFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/IsInfFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/IsNotEmptyFunction.cs
libraries/lokql-engine/InteractiveTableExplorer.cs
libraries/lokql-engine/lokql-engine.csproj
test/BasicTests/SimpleFunctionTests.cs

Fix issue where kql comment treated as break

Add isFinite etc

---

applications/lokqlDx/GridSerializer.cs
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/Preferences.cs
applications/lokqlDx/YesNoCancel.cs
build.ps1

Fix grid serialisation

---

libraries/KustoLoco.Core/Util/TypeMapping.cs
test/BasicTests/DynamicTests.cs

Fixes issues #112 
JsonArrays were not recognised as Dynamic because the lookup path only considered base JsonNodes.

Fix issue with JsonArrays

---

libraries/KustoLoco.Core/InternalRepresentation/Translation/IRTranslator.cs

Improve error message for unimplemented query operators

Improve error message for unimplemented query operators

---

applications/lokqlDx/MainWindow.xaml.cs
docs/tutorials/quickstart.lokql

Fix issue where macros specified in workspace options were not saved

Fix issue where macros specified in workspace options were not saved

---

applications/lokqlDx/WebviewRenderer.cs

Prevent lokqldx datagrid swallowing underscores in column names

---

applications/lokqlDx/MainWindow.xaml
applications/lokqlDx/MainWindow.xaml.cs

datagrid.datetime_format  now controls datagrid datetime format

Allow datetime format in datagrid to be set

---

applications/lokqlDx/MainWindow.xaml.cs

lokqldx - minor tweak to title bar to improve taskbar display

lokqldx - minor tweak to title bar to improve taskbar display

---

applications/lokqlDx/SyntaxHighlighting.xml

Change comment color to light green to make it more legible

Make comments more legible

---

applications/lokqlDx/EditorHelper.cs
applications/lokqlDx/QueryEditor.xaml.cs
docs/tutorials/quickstart.lokql

SHIFT UP/DOWN now moves up/down to next block of text
CTRL-SHIFT-ENTER now executes entire code window

Better navigation

---

applications/lokqlDx/MainWindow.xaml.cs
libraries/KustoLoco.Core/Settings/KustoSettingsProvider.cs
libraries/ScottPlotRendering/ScottPlotKustoResultRenderer.cs

Fix issue where splitters were moved when changing text size

More scottplot customisation.

---

libraries/ScottPlotRendering/ScottPlotKustoResultRenderer.cs

Allow custom palettes for charts

---

libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/RowNumberFunctionImpl.cs
libraries/ScottPlotRendering/ScottPlotKustoResultRenderer.cs
test/BasicTests/SimpleFunctionTests.cs

Add more scottplot customisation

Fix issue with row_number

---

libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInScalarFunctions.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/DateTimeMod.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/DateTimeParts.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/DatetimeAddFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/DatetimeDiffFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/DatetimePartFunction.cs
test/BasicTests/SimpleFunctionTests.cs

Add datetime_add

---

libraries/KustoLoco.Core/Settings/KustoSettingsProvider.cs
libraries/ScottPlotRendering/HeatmapPalette.cs
libraries/ScottPlotRendering/ResultChartAccessor.cs
libraries/ScottPlotRendering/ScottPlotKustoResultRenderer.cs

Allow use of colormaps and explicit color choice in charting

Allow use of colormaps in charting

---

applications/lokqlDx/Chart.xaml
applications/lokqlDx/Chart.xaml.cs
applications/lokqlDx/FlyoutResult.xaml
applications/lokqlDx/MainWindow.xaml
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/ScottPlotter.cs
applications/lokqlDx/WpfRenderingSurface.cs
applications/lokqlDx/lokqlDx.csproj

Support cursor/popups for charts

Chartcursor

---

applications/lokqlDx/QueryEditor.xaml.cs

Driveby refactors

---

libraries/KustoLoco.Core/Settings/KustoSettingsProvider.cs
test/SettingsTests/KustoSettingsTester.cs

Fix issues with set not working in macros

---

libraries/KustoLoco.Core/Evaluation/TreeEvaluator.QueryOperators.Join.cs
libraries/KustoLoco.Core/Util/ChunkHelpers.cs
libraries/KustoLoco.Core/Util/ColumnBuilder.cs
test/CoreTests/EndToEndTests.cs

Optimise join and fix performance regression due to use of StringPool

Optimise join operator

---

libraries/ScottPlotRendering/ResultChartAccessor.cs

Fix exception when rendering chart with one row

---

libraries/KustoLoco.Core/Settings/KustoSettingsProvider.cs

Ensure vars are case-insensitive

---

libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInAggregates.cs

Implement count_distinct and count_distinctif

---

applications/lokqlDx/Chart.xaml.cs
applications/lokqlDx/MainWindow.xaml.cs
applications/lokqlDx/WpfRenderingSurface.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/Aggregates/Helpers/JsonArrayHelper.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInOperators.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/Operators/ContainsCsFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/Operators/ContainsFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/Operators/InOperator.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/Operators/NotContainsCsFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/Operators/NotContainsFunction.cs
libraries/KustoLoco.Core/InternalRepresentation/Nodes/Expressions/IRToScalarExpressionNode.cs
libraries/KustoLoco.Core/InternalRepresentation/Translation/IRTranslator.Expressions.cs
libraries/ScottPlotRendering/ScottPlotKustoResultRenderer.cs
test/BasicTests/SimpleFunctionTests.cs

- HasCs, Has, !Has, !HasCs
- has_any,has_all
- in, in~, !in,!in~

Implement new functions:

---

libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInAggregates.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInOperators.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInWindowFunctions.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInsHelper.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/FunctionFinder.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/Operators/DivideFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/ToDecimalFunction.cs
libraries/KustoLoco.Core/InternalRepresentation/Translation/IRTranslator.Count.cs
libraries/KustoLoco.Core/InternalRepresentation/Translation/IRTranslator.Expressions.cs

Improve overload seleciton by considering return type

Overload selection

---

applications/lokqlDx-Av/Views/Dialogs/MarkdownHelpWindow.axaml
applications/lokqlDx-Av/Views/Dialogs/MarkdownHelpWindow.axaml.cs

Workaround for https://github.com/NeilMacMullen/kusto-loco/issues/270

Force background color to make codeblocks more readable

---

applications/lokqlDx-Av/EditorHelper.cs
applications/lokqlDx-Av/ViewModels/MainViewModel.cs
applications/lokqlDx-Av/ViewModels/QueryEditorViewModel.cs
applications/lokqlDx-Av/Views/QueryEditorView.axaml.cs
applications/lokqlDx/EditorHelper.cs
applications/lokqlDx/Views/QueryEditor.xaml.cs

Simplify query-editor by moving more code into editorhelper

Simplify queryEditory

---

applications/lokqlDx-Av/ViewModels/RenderingSurfaceViewModel.cs
libraries/AppInsightsSupport/ApplicationInsightsLogLoader.cs
libraries/lokql-engine/Commands/AppInsightsCommand.cs

Ensure chart/table determination is made correctly

Allow appinsights to supply tenant-id

---

docs/simple-powershell-kql-samples.md

This gives documentation on more  Simple PSKQL PowerShell Samples
It fixes issue #281

fix : Documentation - new sample applications

---

Directory.Packages.props
applications/lokqlDx/ViewModels/MainViewModel.cs
samples/CustomFunctions/nCrunchTemp_ccefc8e3-1206-45c3-b89d-ea5f882f6eac.csproj
test/lokqlDxComponentsTests/lokqlDxComponentsTests.csproj

Update nuget packages

---

applications/lokqlDx/Services/DialogService.cs
applications/lokqlDx/Views/Dialogs/ApplicationPreferencesView.axaml
applications/lokqlDx/Views/Dialogs/WorkspacePreferencesView.axaml

Ensure preferences dialogs are not too large

---

libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInScalarFunctions.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/Bin.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/RandFunctionImpl.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/todatetimefunction.cs
libraries/KustoLoco.Core/Evaluation/TreeEvaluator.Expressions.FunctionCalls.cs
test/BasicTests/ArgMinMaxTests.cs
test/BasicTests/DateTimeTests.cs
test/BasicTests/IgnoredTests.cs
test/BasicTests/RandTests.cs
test/BasicTests/SimpleFunctionTests.cs

Fixup corner-case implementations of rand and bin

---

applications/lokqlDx/ViewModels/RenderingSurfaceViewModel.cs
applications/lokqlDx/Views/RenderingSurfaceView.axaml

Add CSV copy option to context menu

---

applications/lokqlDx/Models/YesNoCancel.cs
applications/lokqlDx/ViewModels/MainViewModel.cs

Fix issue where closing couldn'tbe cancelled

---

applications/lokqlDx/Styles/ButtonGlyphStyle.axaml
applications/lokqlDx/ViewModels/RenderingSurfaceViewModel.cs
applications/lokqlDx/Views/ChartView.axaml.cs
applications/lokqlDx/Views/MapView.axaml
applications/lokqlDx/Views/MapView.axaml.cs
applications/lokqlDx/Views/RenderingSurfaceView.axaml
applications/lokqlDx/Views/RenderingSurfaceView.axaml.cs

Fix Avalonia race-conditions in release build

Timing issues

---

applications/lokqlDx/ViewModels/ChartViewModel.cs
applications/lokqlDx/ViewModels/QueryViewModel.cs
applications/lokqlDx/ViewModels/RenderingSurfaceViewModel.cs
applications/lokqlDx/Views/ChartView.axaml
applications/lokqlDx/Views/ChartView.axaml.cs
applications/lokqlDx/Views/QueryView.axaml
applications/lokqlDx/Views/RenderingSurfaceView.axaml.cs
docs/tutorials/chart-demo.lokql
libraries/ScottPlotRendering/RenderInfo.cs
libraries/ScottPlotRendering/RenderInfoBuilder.cs
libraries/ScottPlotRendering/ScottPlotKustoResultRenderer.cs

Lock Y axis by default

---

applications/lokqlDx/Assets/IntellisenseFunctions.json
applications/lokqlDx/Assets/SyntaxHighlighting.xml
libraries/KustoLoco.Core/Evaluation/BuiltIns/BuiltInsHelper.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/CustomFunctions.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/FormatFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/FormatInterpFunction.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/Heatmap.cs
libraries/KustoLoco.Core/Evaluation/BuiltIns/ScalarFunctions/HeatmapColorFunction.cs
libraries/KustoLoco.Core/Evaluation/TreeEvaluator.Expressions.Cast.cs
libraries/KustoLoco.Core/Util/TypeMapping.cs
libraries/lokqlDxComponents/Views/Dialogs/CompletionWindowWrapper.cs
nuke.ps1
sourceGeneration/SourceGeneration/Param.cs
sourceGeneration/SourceGeneration/ParamGeneneration.cs
test/BasicTests/DateTimeTests.cs
test/BasicTests/SimpleFunctionTests.cs

Support 
- format(1234,"X")
- format_interp("hex {0:X} dec {0:X} guid {0:N}",1234,new_guid())

Support format and format_interp
